Document: tuntox
Title: Debian tuntox Manual
Author: <insert document author here>
Abstract: This manual describes what tuntox is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/tuntox/tuntox.sgml.gz

Format: postscript
Files: /usr/share/doc/tuntox/tuntox.ps.gz

Format: text
Files: /usr/share/doc/tuntox/tuntox.text.gz

Format: HTML
Index: /usr/share/doc/tuntox/html/index.html
Files: /usr/share/doc/tuntox/html/*.html
